### ISSUE TITLE
EfficientNet 생성_혜영

### ISSUE THREAD

**Issue by hyeyoung-x** [pladata-encore/DA36-mini3-dl3#10]
## 🌈 Success criteria

1. 데이터로드
2. 프로토타입 EfficientNet 모델 생성

## 👷 To-do

- [x] 데이터 로드하기(쓰레기이미지)
- [x] Sequence객체 만들기
- [x] finn-tuning 조정해보기
- [ ] 데이터 증강 해보기
- [x] 하이퍼파라미터 조정해보기

## 🧶 Review

- data_load 하는 과정에서 폴더-폴더의 연속이라 불러오는데 어려웠음
- Sequence에서 print하면 sequence 객체 불러올 때 출력 결과가 지저분하게 나옴! (확인할거 확인하고 print는 지우기!)
- encoding 했으면... encoding한걸... 써먹자....
- fine-tuning 조정 실패!

**Comment by shqkel** [comment]
"encoding 했으면... encoding한걸... 써먹자...." 
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
