### ISSUE TITLE
Streamlit 구현

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36-mini3-dl3#17]
## 🌈 Success criteria

1. 프로그램을 Streamlit상에 구현한다. 

## 👷 To-do

- [x] 할일 1 : 가장 잘 훈련된 모델을 저장하고 GoogleDrive에 업로드한다.
- [ ] 할일 2 : 해당 모델을 Streamlit상에서 다운로드하여 예측값을 출력하는 로직을 구현한다.
- [ ] 할일 3 : UI(이미지 입력, 결과 출력창 등)를 구현한다.
